name: timur_harin
description: Timur Harin
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  flutter_launcher_icons: ^0.13.1
  auto_size_text: ^3.0.0
  responsive_framework: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon2.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icons/icon2.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  macos:
    generate: true
    image_path: "assets/icons/icon2.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
   - family: JetBrainsMono
     fonts:
       - asset: fonts/JetBrainsMono-Regular.ttf
       - asset: fonts/JetBrainsMono-Bold.ttf
         weight: 700